export const ACTION_TYPE = {
  FETCH_MOVIES: "FETCH_MOVIES",
  FETCH_TV_MOVIES: "FETCH_TV_MOVIES",
  FETCH_ACTION_MOVIES: "FETCH_ACTION_MOVIES",
  SELECTED_MOVIES: "SELECTED_MOVIES",
  REMOVE_FETCHED_MOVIES: "REMOVE_FETCHED_MOVIES",
};
