export const  ACTION_TYPE= {
  CAUROSEAL_TV_MOVIES:"CAUROSEAL_TV_MOVIES",
  CAUROSEAL_MOVIES:"CAUROSEAL_MOVIES",
  FETCH_MOVIES:"FETCH_MOVIES",
  FETCH_TV_MOVIES:"FETCH_TV_MOVIES",
  SELECTED_MOVIES:"SELECTED_MOVIES",
  REMOVE_FETCHED_MOVIES:"REMOVE_FETCHED_MOVIES"
}